name: matply
homepage: https://www.robot-shadow.cn/src/pkg/MatPly_Dart/site/
description: "Dart Matrix realized by C Dll"

repository: https://github.com/PythonnotJava/MatPly

version: 1.0.9
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  ffi: ^2.1.2
  path: ^1.9.0

platforms:
  windows:
  android:
  linux: