name: matply

description: "Dart Matrix realized by C Dll"

repository: https://github.com/PythonnotJava/MatPly

version: 1.0.5
environment:
  sdk: '^3.4.3'

dependencies:
  ffi: ^2.1.2
  path: ^1.9.0
